name: kanebo_mobile
description: Kanebo - Money Manager. Aplikasi manajemen keuangan personal yang colorful & playful.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # State management
  provider: ^6.1.2

  # UI & UX
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0

  # Monetisasi (iklan AdMob)
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
